services:
  postgres:
    image: postgres:15-alpine
    container_name: gougle-docs-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gougle-docs-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: gougle-docs-backend
    environment:
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - gougle-docs-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: gougle-docs-frontend
    environment:
      PUBLIC_API_URL: ${PUBLIC_API_URL}
      PUBLIC_SOCKET_URL: ${PUBLIC_SOCKET_URL}
      INTERNAL_API_URL: ${INTERNAL_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - gougle-docs-network
      - npm

volumes:
  postgres_data:

networks:
  gougle-docs-network:
    driver: bridge
  npm:
    external: true
    name: nginx-proxy-manager-stack_default