import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import Header from '@/components/Header/Header';
import { TooltipProvider } from '@/components/ui/tooltip';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh flex flex-col`}
            >
                <TooltipProvider>
                    <Header />
                    <main className="py-6 px-10 container mx-auto flex-1">
                        {children}
                    </main>
                    <Toaster
                        position="top-center"
                        richColors
                        expand={false}
                        duration={8000}
                    />
                </TooltipProvider>
            </body>
        </html>
    );
}
